"""add  category orm_02

Revision ID: 405f39ba329d
Revises: cabe48b69349
Create Date: 2025-08-29 12:03:08.841171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '405f39ba329d'
down_revision: Union[str, Sequence[str], None] = 'cabe48b69349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'tag2')
    op.drop_column('user', 'secret_name2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('secret_name2', sa.VARCHAR(), nullable=False))
    op.add_column('category', sa.Column('tag2', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
