"""add  category orm_03

Revision ID: a44f83d3465f
Revises: 405f39ba329d
Create Date: 2025-08-29 12:05:09.249322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a44f83d3465f'
down_revision: Union[str, Sequence[str], None] = '405f39ba329d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_age'), table_name='test')
    op.drop_index(op.f('ix_test_name'), table_name='test')
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_name'), 'test', ['name'], unique=False)
    op.create_index(op.f('ix_test_age'), 'test', ['age'], unique=False)
    # ### end Alembic commands ###
